services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USER}'
    ports:
      - '5433:5432'